development:
  adapter: postgresql
  encoding: utf8
  database: clevercode_professionals_development
  pool: 5
  username: Solitude
  password: ''
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: clevercode_professionals_test
  pool: 5
  username: Solitude
  password: ''
  host: localhost
